package domain;
// Generated 2018-2-20 17:37:47 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TLaw generated by hbm2java
 */
@Entity
@Table(name = "t_law", catalog = "law")
public class TLaw implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5881556606740975980L;
	private Integer lawId;
	private String fullName;
	private String organ;
	private String referenceNo;
	private Date publishDate;
	private Date effectiveDate;
	private String prescription;
	private String hierarchy;
	private String classification;
	private String aliases;
	private String fullPathName;

	public TLaw() {
	}

	public TLaw(String fullName, String organ, Date effectiveDate, String prescription, String hierarchy,
			String classification) {
		this.fullName = fullName;
		this.organ = organ;
		this.effectiveDate = effectiveDate;
		this.prescription = prescription;
		this.hierarchy = hierarchy;
		this.classification = classification;
	}

	public TLaw(String fullName, String organ, String referenceNo, Date publishDate, Date effectiveDate,
			String prescription, String hierarchy, String classification, String aliases, String fullPathName) {
		this.fullName = fullName;
		this.organ = organ;
		this.referenceNo = referenceNo;
		this.publishDate = publishDate;
		this.effectiveDate = effectiveDate;
		this.prescription = prescription;
		this.hierarchy = hierarchy;
		this.classification = classification;
		this.aliases = aliases;
		this.fullPathName = fullPathName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lawId", unique = true, nullable = false)
	public Integer getLawId() {
		return this.lawId;
	}

	public void setLawId(Integer lawId) {
		this.lawId = lawId;
	}

	@Column(name = "fullName", nullable = false, length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "organ", nullable = false, length = 50)
	public String getOrgan() {
		return this.organ;
	}

	public void setOrgan(String organ) {
		this.organ = organ;
	}

	@Column(name = "referenceNo", length = 50)
	public String getReferenceNo() {
		return this.referenceNo;
	}

	public void setReferenceNo(String referenceNo) {
		this.referenceNo = referenceNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publishDate", length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effectiveDate", nullable = false, length = 10)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Column(name = "prescription", nullable = false, length = 5)
	public String getPrescription() {
		return this.prescription;
	}

	public void setPrescription(String prescription) {
		this.prescription = prescription;
	}

	@Column(name = "hierarchy", nullable = false, length = 11)
	public String getHierarchy() {
		return this.hierarchy;
	}

	public void setHierarchy(String hierarchy) {
		this.hierarchy = hierarchy;
	}

	@Column(name = "classification", nullable = false, length = 20)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "aliases", length = 500)
	public String getAliases() {
		return this.aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}

	@Column(name = "fullPathName")
	public String getFullPathName() {
		return this.fullPathName;
	}

	public void setFullPathName(String fullPathName) {
		this.fullPathName = fullPathName;
	}

}
